/*
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:
     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/

#include <stdio.h>
#include <math.h>       /* sqrt */
#include <time.h>

unsigned seventh_triangle_number(unsigned prev_seventh,unsigned prev_seventh_value,unsigned value);
unsigned factors(unsigned value);
unsigned get_seventh_triangle_number_over_divisors(unsigned value);

int main(){

    clock_t start = clock();

    //! Real start of the program 
  
    printf("%d\n",get_seventh_triangle_number_over_divisors(5));
    printf("%d\n",get_seventh_triangle_number_over_divisors(500));

    //! Final of the program
    clock_t stop = clock();
    double time_spent = (double)(stop - start) / CLOCKS_PER_SEC;
    printf("Elapsed %.2f ms \n", time_spent*1000);

    return 0;
}

unsigned seventh_triangle_number(unsigned prev_seventh,unsigned prev_seventh_value,unsigned value){
    unsigned seventh = prev_seventh_value;
    for (unsigned i=prev_seventh+1; i<value+1; i++){
        seventh = seventh + i;
    }
    return seventh;
}

unsigned factors_len(unsigned value){

    long double temp1 = sqrt(value);
    unsigned temp2 = (int)temp1;
    unsigned counter = 2;
    for (unsigned i=2; i<temp2; i++){
        if(value%i==0){
            counter = counter + 2;
        }
    }
    if(temp1==temp2)
        counter++;

    return counter;
}


unsigned get_seventh_triangle_number_over_divisors(unsigned value){

    unsigned divisors = 0;
    unsigned seventh_value = 1;
    unsigned seventh_index = 1;
    while(1){
        divisors = factors_len(seventh_value);
        if (divisors >= value)
            break;
        seventh_index++;
        seventh_value = seventh_triangle_number(seventh_index-1, seventh_value, seventh_index);
    }
    return seventh_value;
}
//print(get_seventh_triangle_number_over_divisors(5))      #28        //0.000033 s
//print(get_seventh_triangle_number_over_divisors(50))     #25200 //0.000904 s    //0.041302 s
//print(get_seventh_triangle_number_over_divisors(100))   #73920      //0.203230 s
//print(get_seventh_triangle_number_over_divisors(200))   #2031120  //0.049273 s  // 30.082121 s
//print(get_seventh_triangle_number_over_divisors(300))   #2162160 // 0.052654 s //32 s
//print(get_seventh_triangle_number_over_divisors(500))   #76576500 //1.684446 s
