//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

let stopWatch = System.Diagnostics.Stopwatch.StartNew()

let mutable b = 2
let mutable a = 1
let mutable c = 3
let mutable sum_of_even = 2
let mutable i = 3
let mutable loop_b = true

while loop_b  do 
    if i >= 4000000 then 
        loop_b <-false
    c <- a + b
    a <- b
    b <- c
    i <- c
    if c%2 = 0 then
        sum_of_even <- sum_of_even + c
        printf "%d " c
done
printfn
printfn "%d" sum_of_even

stopWatch.Stop()
printfn "Elapsed %f ms" stopWatch.Elapsed.TotalMilliseconds
